namespace Quality.Forms.Doctor
{
    partial class DoctorDashboardForm
    {
        private System.ComponentModel.IContainer components = null; private System.Windows.Forms.Label lblUser; private System.Windows.Forms.TabControl tabMain; private System.Windows.Forms.TabPage tabPatients; private System.Windows.Forms.TabPage tabAppointments; private System.Windows.Forms.TabPage tabHistory; private System.Windows.Forms.DataGridView gridPatients; private System.Windows.Forms.DataGridView gridAppointments; private System.Windows.Forms.DataGridView gridHistory; private System.Windows.Forms.Button btnNewPatient; private System.Windows.Forms.Button btnEditPatient; private System.Windows.Forms.Button btnDeletePatient; private System.Windows.Forms.Button btnNewAppointment; private System.Windows.Forms.Button btnEditAppointment; private System.Windows.Forms.Button btnDeleteAppointment; private System.Windows.Forms.Button btnSurvey;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.lblUser = new System.Windows.Forms.Label(); this.tabMain = new System.Windows.Forms.TabControl(); this.tabPatients = new System.Windows.Forms.TabPage(); this.btnDeletePatient = new System.Windows.Forms.Button(); this.btnEditPatient = new System.Windows.Forms.Button(); this.btnNewPatient = new System.Windows.Forms.Button(); this.gridPatients = new System.Windows.Forms.DataGridView(); this.tabAppointments = new System.Windows.Forms.TabPage(); this.btnDeleteAppointment = new System.Windows.Forms.Button(); this.btnEditAppointment = new System.Windows.Forms.Button(); this.btnSurvey = new System.Windows.Forms.Button(); this.btnNewAppointment = new System.Windows.Forms.Button(); this.gridAppointments = new System.Windows.Forms.DataGridView(); this.tabHistory = new System.Windows.Forms.TabPage(); this.gridHistory = new System.Windows.Forms.DataGridView(); this.tabMain.SuspendLayout(); this.tabPatients.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridPatients)).BeginInit(); this.tabAppointments.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridAppointments)).BeginInit(); this.tabHistory.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridHistory)).BeginInit(); this.SuspendLayout();
            this.lblUser.AutoSize = true; this.lblUser.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold); this.lblUser.Location = new System.Drawing.Point(20, 17); this.lblUser.Text = "Врач";
            this.tabMain.Controls.Add(this.tabPatients); this.tabMain.Controls.Add(this.tabAppointments); this.tabMain.Controls.Add(this.tabHistory); this.tabMain.Location = new System.Drawing.Point(20, 57); this.tabMain.Size = new System.Drawing.Size(1040, 540);
            this.tabPatients.Controls.Add(this.btnDeletePatient); this.tabPatients.Controls.Add(this.btnEditPatient); this.tabPatients.Controls.Add(this.btnNewPatient); this.tabPatients.Controls.Add(this.gridPatients); this.tabPatients.Text = "Пациенты"; this.tabPatients.UseVisualStyleBackColor = true;
            this.btnNewPatient.BackColor = System.Drawing.Color.Gainsboro; this.btnNewPatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnNewPatient.Location = new System.Drawing.Point(15, 15); this.btnNewPatient.Size = new System.Drawing.Size(170, 36); this.btnNewPatient.Text = "Новый пациент"; this.btnNewPatient.Click += new System.EventHandler(this.btnNewPatient_Click);
            this.btnEditPatient.BackColor = System.Drawing.Color.Gainsboro; this.btnEditPatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnEditPatient.Location = new System.Drawing.Point(191, 15); this.btnEditPatient.Size = new System.Drawing.Size(170, 36); this.btnEditPatient.Text = "Редактировать"; this.btnEditPatient.Click += new System.EventHandler(this.btnEditPatient_Click);
            this.btnDeletePatient.BackColor = System.Drawing.Color.Gainsboro; this.btnDeletePatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnDeletePatient.Location = new System.Drawing.Point(367, 15); this.btnDeletePatient.Size = new System.Drawing.Size(170, 36); this.btnDeletePatient.Text = "Удалить"; this.btnDeletePatient.Click += new System.EventHandler(this.btnDeletePatient_Click);
            this.gridPatients.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridPatients.Location = new System.Drawing.Point(15, 61); this.gridPatients.ReadOnly = true; this.gridPatients.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; this.gridPatients.MultiSelect = false; this.gridPatients.Size = new System.Drawing.Size(1000, 430);
            this.tabAppointments.Controls.Add(this.btnDeleteAppointment); this.tabAppointments.Controls.Add(this.btnEditAppointment); this.tabAppointments.Controls.Add(this.btnSurvey); this.tabAppointments.Controls.Add(this.btnNewAppointment); this.tabAppointments.Controls.Add(this.gridAppointments); this.tabAppointments.Text = "Приёмы"; this.tabAppointments.UseVisualStyleBackColor = true;
            this.btnNewAppointment.BackColor = System.Drawing.Color.Gainsboro; this.btnNewAppointment.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnNewAppointment.Location = new System.Drawing.Point(15, 15); this.btnNewAppointment.Size = new System.Drawing.Size(170, 36); this.btnNewAppointment.Text = "Новый приём"; this.btnNewAppointment.Click += new System.EventHandler(this.btnNewAppointment_Click);
            this.btnEditAppointment.BackColor = System.Drawing.Color.Gainsboro; this.btnEditAppointment.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnEditAppointment.Location = new System.Drawing.Point(191, 15); this.btnEditAppointment.Size = new System.Drawing.Size(170, 36); this.btnEditAppointment.Text = "Редактировать"; this.btnEditAppointment.Click += new System.EventHandler(this.btnEditAppointment_Click);
            this.btnDeleteAppointment.BackColor = System.Drawing.Color.Gainsboro; this.btnDeleteAppointment.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnDeleteAppointment.Location = new System.Drawing.Point(367, 15); this.btnDeleteAppointment.Size = new System.Drawing.Size(170, 36); this.btnDeleteAppointment.Text = "Удалить"; this.btnDeleteAppointment.Click += new System.EventHandler(this.btnDeleteAppointment_Click);
            this.btnSurvey.BackColor = System.Drawing.Color.Gainsboro; this.btnSurvey.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnSurvey.Location = new System.Drawing.Point(543, 15); this.btnSurvey.Size = new System.Drawing.Size(210, 36); this.btnSurvey.Text = "Оценка качества"; this.btnSurvey.Click += new System.EventHandler(this.btnSurvey_Click);
            this.gridAppointments.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridAppointments.Location = new System.Drawing.Point(15, 61); this.gridAppointments.ReadOnly = true; this.gridAppointments.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; this.gridAppointments.MultiSelect = false; this.gridAppointments.Size = new System.Drawing.Size(1000, 430);
            this.tabHistory.Controls.Add(this.gridHistory); this.tabHistory.Text = "История"; this.tabHistory.UseVisualStyleBackColor = true;
            this.gridHistory.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridHistory.Location = new System.Drawing.Point(15, 15); this.gridHistory.ReadOnly = true; this.gridHistory.Size = new System.Drawing.Size(1000, 476);
            this.ClientSize = new System.Drawing.Size(1084, 621); this.Controls.Add(this.tabMain); this.Controls.Add(this.lblUser); this.Name = "DoctorDashboardForm"; this.Text = "Quality - Врач"; this.Load += new System.EventHandler(this.DoctorDashboardForm_Load);
            this.tabMain.ResumeLayout(false); this.tabPatients.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridPatients)).EndInit(); this.tabAppointments.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridAppointments)).EndInit(); this.tabHistory.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridHistory)).EndInit(); this.ResumeLayout(false); this.PerformLayout();
        }
    }
}
