namespace Quality.Forms.QualityManager
{
    partial class QualityManagerDashboardForm
    {
        private System.ComponentModel.IContainer components = null; private System.Windows.Forms.Label lblUser; private System.Windows.Forms.TabControl tabMain; private System.Windows.Forms.TabPage tabIndicators; private System.Windows.Forms.TabPage tabSurveys; private System.Windows.Forms.TabPage tabActions; private System.Windows.Forms.TabPage tabReports; private System.Windows.Forms.DataGridView gridIndicators; private System.Windows.Forms.DataGridView gridSurveys; private System.Windows.Forms.DataGridView gridActions; private System.Windows.Forms.TextBox txtReports; private System.Windows.Forms.Button btnNewAction; private System.Windows.Forms.Button btnEditAction; private System.Windows.Forms.Button btnDeleteAction;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.lblUser = new System.Windows.Forms.Label(); this.tabMain = new System.Windows.Forms.TabControl(); this.tabIndicators = new System.Windows.Forms.TabPage(); this.gridIndicators = new System.Windows.Forms.DataGridView(); this.tabSurveys = new System.Windows.Forms.TabPage(); this.gridSurveys = new System.Windows.Forms.DataGridView(); this.tabActions = new System.Windows.Forms.TabPage(); this.btnDeleteAction = new System.Windows.Forms.Button(); this.btnEditAction = new System.Windows.Forms.Button(); this.btnNewAction = new System.Windows.Forms.Button(); this.gridActions = new System.Windows.Forms.DataGridView(); this.tabReports = new System.Windows.Forms.TabPage(); this.txtReports = new System.Windows.Forms.TextBox(); this.tabMain.SuspendLayout(); this.tabIndicators.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridIndicators)).BeginInit(); this.tabSurveys.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridSurveys)).BeginInit(); this.tabActions.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridActions)).BeginInit(); this.tabReports.SuspendLayout(); this.SuspendLayout();
            this.lblUser.AutoSize = true; this.lblUser.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold); this.lblUser.Location = new System.Drawing.Point(20, 17); this.lblUser.Text = "Менеджер по качеству";
            this.tabMain.Controls.Add(this.tabIndicators); this.tabMain.Controls.Add(this.tabSurveys); this.tabMain.Controls.Add(this.tabActions); this.tabMain.Controls.Add(this.tabReports); this.tabMain.Location = new System.Drawing.Point(20, 57); this.tabMain.Size = new System.Drawing.Size(1040, 540);
            this.tabIndicators.Controls.Add(this.gridIndicators); this.tabIndicators.Text = "Показатели"; this.tabIndicators.UseVisualStyleBackColor = true;
            this.gridIndicators.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridIndicators.Location = new System.Drawing.Point(15, 15); this.gridIndicators.ReadOnly = true; this.gridIndicators.Size = new System.Drawing.Size(1000, 476);
            this.tabSurveys.Controls.Add(this.gridSurveys); this.tabSurveys.Text = "Опросы"; this.tabSurveys.UseVisualStyleBackColor = true;
            this.gridSurveys.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridSurveys.Location = new System.Drawing.Point(15, 15); this.gridSurveys.ReadOnly = true; this.gridSurveys.Size = new System.Drawing.Size(1000, 476);
            this.tabActions.Controls.Add(this.btnDeleteAction); this.tabActions.Controls.Add(this.btnEditAction); this.tabActions.Controls.Add(this.btnNewAction); this.tabActions.Controls.Add(this.gridActions); this.tabActions.Text = "Действия"; this.tabActions.UseVisualStyleBackColor = true;
            this.btnNewAction.BackColor = System.Drawing.Color.Gainsboro; this.btnNewAction.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnNewAction.Location = new System.Drawing.Point(15, 15); this.btnNewAction.Size = new System.Drawing.Size(160, 36); this.btnNewAction.Text = "Создать"; this.btnNewAction.Click += new System.EventHandler(this.btnNewAction_Click);
            this.btnEditAction.BackColor = System.Drawing.Color.Gainsboro; this.btnEditAction.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnEditAction.Location = new System.Drawing.Point(181, 15); this.btnEditAction.Size = new System.Drawing.Size(160, 36); this.btnEditAction.Text = "Редактировать"; this.btnEditAction.Click += new System.EventHandler(this.btnEditAction_Click);
            this.btnDeleteAction.BackColor = System.Drawing.Color.Gainsboro; this.btnDeleteAction.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnDeleteAction.Location = new System.Drawing.Point(347, 15); this.btnDeleteAction.Size = new System.Drawing.Size(160, 36); this.btnDeleteAction.Text = "Удалить"; this.btnDeleteAction.Click += new System.EventHandler(this.btnDeleteAction_Click);
            this.gridActions.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridActions.Location = new System.Drawing.Point(15, 60); this.gridActions.ReadOnly = true; this.gridActions.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; this.gridActions.MultiSelect = false; this.gridActions.Size = new System.Drawing.Size(1000, 431);
            this.tabReports.Controls.Add(this.txtReports); this.tabReports.Text = "Отчёты"; this.tabReports.UseVisualStyleBackColor = true;
            this.txtReports.Location = new System.Drawing.Point(15, 15); this.txtReports.Multiline = true; this.txtReports.ReadOnly = true; this.txtReports.Size = new System.Drawing.Size(720, 260); this.txtReports.Text = "SQL-аналитика для диплома:\r\n- средняя оценка по отделениям\r\n- динамика качества по месяцам\r\n- просроченные корректирующие действия\r\n- популярные медицинские услуги\r\n- врачи с высокой оценкой";
            this.ClientSize = new System.Drawing.Size(1084, 621); this.Controls.Add(this.tabMain); this.Controls.Add(this.lblUser); this.Name = "QualityManagerDashboardForm"; this.Text = "Quality - Менеджер по качеству"; this.Load += new System.EventHandler(this.QualityManagerDashboardForm_Load);
            this.tabMain.ResumeLayout(false); this.tabIndicators.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridIndicators)).EndInit(); this.tabSurveys.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridSurveys)).EndInit(); this.tabActions.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridActions)).EndInit(); this.tabReports.ResumeLayout(false); this.tabReports.PerformLayout(); this.ResumeLayout(false); this.PerformLayout();
        }
    }
}
