namespace Quality.Forms.Admin
{
    partial class AdminDashboardForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label lblUser; private System.Windows.Forms.TabControl tabMain; private System.Windows.Forms.TabPage tabUsers; private System.Windows.Forms.TabPage tabDepartments; private System.Windows.Forms.TabPage tabDashboard; private System.Windows.Forms.DataGridView gridUsers; private System.Windows.Forms.DataGridView gridDepartments; private System.Windows.Forms.DataGridView gridStats; private System.Windows.Forms.Button btnAddUser; private System.Windows.Forms.Button btnEditUser; private System.Windows.Forms.Button btnDeleteUser; private System.Windows.Forms.Button btnAddDepartment; private System.Windows.Forms.Button btnEditDepartment; private System.Windows.Forms.Button btnDeleteDepartment;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.lblUser = new System.Windows.Forms.Label(); this.tabMain = new System.Windows.Forms.TabControl(); this.tabUsers = new System.Windows.Forms.TabPage(); this.btnDeleteUser = new System.Windows.Forms.Button(); this.btnEditUser = new System.Windows.Forms.Button(); this.btnAddUser = new System.Windows.Forms.Button(); this.gridUsers = new System.Windows.Forms.DataGridView(); this.tabDepartments = new System.Windows.Forms.TabPage(); this.btnDeleteDepartment = new System.Windows.Forms.Button(); this.btnEditDepartment = new System.Windows.Forms.Button(); this.btnAddDepartment = new System.Windows.Forms.Button(); this.gridDepartments = new System.Windows.Forms.DataGridView(); this.tabDashboard = new System.Windows.Forms.TabPage(); this.gridStats = new System.Windows.Forms.DataGridView(); this.tabMain.SuspendLayout(); this.tabUsers.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).BeginInit(); this.tabDepartments.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridDepartments)).BeginInit(); this.tabDashboard.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.gridStats)).BeginInit(); this.SuspendLayout();
            this.lblUser.AutoSize = true; this.lblUser.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold); this.lblUser.Location = new System.Drawing.Point(20, 17); this.lblUser.Text = "Администратор";
            this.tabMain.Controls.Add(this.tabUsers); this.tabMain.Controls.Add(this.tabDepartments); this.tabMain.Controls.Add(this.tabDashboard); this.tabMain.Location = new System.Drawing.Point(20, 57); this.tabMain.Size = new System.Drawing.Size(1040, 540);
            this.tabUsers.Controls.Add(this.btnDeleteUser); this.tabUsers.Controls.Add(this.btnEditUser); this.tabUsers.Controls.Add(this.btnAddUser); this.tabUsers.Controls.Add(this.gridUsers); this.tabUsers.Text = "Пользователи"; this.tabUsers.UseVisualStyleBackColor = true;
            this.btnAddUser.BackColor = System.Drawing.Color.Gainsboro; this.btnAddUser.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnAddUser.Location = new System.Drawing.Point(15, 14); this.btnAddUser.Size = new System.Drawing.Size(155, 36); this.btnAddUser.Text = "Добавить"; this.btnAddUser.Click += new System.EventHandler(this.btnAddUser_Click);
            this.btnEditUser.BackColor = System.Drawing.Color.Gainsboro; this.btnEditUser.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnEditUser.Location = new System.Drawing.Point(176, 14); this.btnEditUser.Size = new System.Drawing.Size(155, 36); this.btnEditUser.Text = "Редактировать"; this.btnEditUser.Click += new System.EventHandler(this.btnEditUser_Click);
            this.btnDeleteUser.BackColor = System.Drawing.Color.Gainsboro; this.btnDeleteUser.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnDeleteUser.Location = new System.Drawing.Point(337, 14); this.btnDeleteUser.Size = new System.Drawing.Size(155, 36); this.btnDeleteUser.Text = "Удалить"; this.btnDeleteUser.Click += new System.EventHandler(this.btnDeleteUser_Click);
            this.gridUsers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridUsers.Location = new System.Drawing.Point(15, 63); this.gridUsers.ReadOnly = true; this.gridUsers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; this.gridUsers.MultiSelect = false; this.gridUsers.Size = new System.Drawing.Size(1000, 430);
            this.tabDepartments.Controls.Add(this.btnDeleteDepartment); this.tabDepartments.Controls.Add(this.btnEditDepartment); this.tabDepartments.Controls.Add(this.btnAddDepartment); this.tabDepartments.Controls.Add(this.gridDepartments); this.tabDepartments.Text = "Отделения"; this.tabDepartments.UseVisualStyleBackColor = true;
            this.btnAddDepartment.BackColor = System.Drawing.Color.Gainsboro; this.btnAddDepartment.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnAddDepartment.Location = new System.Drawing.Point(15, 14); this.btnAddDepartment.Size = new System.Drawing.Size(155, 36); this.btnAddDepartment.Text = "Добавить"; this.btnAddDepartment.Click += new System.EventHandler(this.btnAddDepartment_Click);
            this.btnEditDepartment.BackColor = System.Drawing.Color.Gainsboro; this.btnEditDepartment.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnEditDepartment.Location = new System.Drawing.Point(176, 14); this.btnEditDepartment.Size = new System.Drawing.Size(155, 36); this.btnEditDepartment.Text = "Редактировать"; this.btnEditDepartment.Click += new System.EventHandler(this.btnEditDepartment_Click);
            this.btnDeleteDepartment.BackColor = System.Drawing.Color.Gainsboro; this.btnDeleteDepartment.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnDeleteDepartment.Location = new System.Drawing.Point(337, 14); this.btnDeleteDepartment.Size = new System.Drawing.Size(155, 36); this.btnDeleteDepartment.Text = "Удалить"; this.btnDeleteDepartment.Click += new System.EventHandler(this.btnDeleteDepartment_Click);
            this.gridDepartments.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridDepartments.Location = new System.Drawing.Point(15, 63); this.gridDepartments.ReadOnly = true; this.gridDepartments.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; this.gridDepartments.MultiSelect = false; this.gridDepartments.Size = new System.Drawing.Size(1000, 430);
            this.tabDashboard.Controls.Add(this.gridStats); this.tabDashboard.Text = "Дашборд"; this.tabDashboard.UseVisualStyleBackColor = true;
            this.gridStats.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.gridStats.Location = new System.Drawing.Point(15, 15); this.gridStats.ReadOnly = true; this.gridStats.Size = new System.Drawing.Size(470, 210);
            this.ClientSize = new System.Drawing.Size(1084, 621); this.Controls.Add(this.tabMain); this.Controls.Add(this.lblUser); this.Name = "AdminDashboardForm"; this.Text = "Quality - Администратор"; this.Load += new System.EventHandler(this.AdminDashboardForm_Load);
            this.tabMain.ResumeLayout(false); this.tabUsers.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).EndInit(); this.tabDepartments.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridDepartments)).EndInit(); this.tabDashboard.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.gridStats)).EndInit(); this.ResumeLayout(false); this.PerformLayout();
        }
    }
}
